### ISSUE TITLE
Issue launching Briefer using docker-compose.dev.yaml

### ISSUE THREAD

**Issue by eluyutao** [briefercloud/briefer#118]
Hi, I'd like to launch using docker-compose.dev.yaml file with following comamnd
`docker-compose -f docker-compose.dev.yaml up`
but it failed with plenty of warning messages and a critical error.

### some warnings:
`#13 0.227  WARNING  No locally installed `turbo` found. Using version: 2.1.2.
#16 34.57 warning lru.min@1.1.0: The engine "bun" appears to be invalid.
#16 34.57 warning lru.min@1.1.0: The engine "deno" appears to be invalid.
#16 34.58 [3/4] Linking dependencies...
#16 34.58 warning "eslint-config-custom > eslint-config-next@12.3.4" has unmet peer dependency "eslint@^7.23.0 || ^8.0.0".
#16 34.58 warning "eslint-config-custom > eslint-config-prettier@8.10.0" has unmet peer dependency "eslint@>=7.0.0".
#16 34.58 warning "eslint-config-custom > eslint-plugin-react@7.28.0" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".`

### and errors:
`#16 40.26 warning Error running install script for optional dependency: "/app/node_modules/cpu-features: Command failed.
#16 40.26 Exit code: 1
#16 40.26 Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
#16 40.26 Arguments: 
#16 40.26 Directory: /app/node_modules/cpu-features
#16 40.26 Output:
#16 40.26 /app/node_modules/buildcheck/lib/index.js:115
#16 40.26   throw new Error('Unable to detect compiler type');
#16 40.26   ^
#16 40.26 
#16 40.26 Error: Unable to detect compiler type
#16 40.26     at BuildEnvironment.getKind (/app/node_modules/buildcheck/lib/index.js:115:9)
#16 40.26     at BuildEnvironment.tryCompile (/app/node_modules/buildcheck/lib/index.js:537:15)
#16 40.26     at BuildEnvironment.checkHeader (/app/node_modules/buildcheck/lib/index.js:423:25)
#16 40.26     at Object.<anonymous> (/app/node_modules/cpu-features/buildcheck.js:16:4)
#16 40.26     at Module._compile (node:internal/modules/cjs/loader:1364:14)
#16 40.26     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
#16 40.26     at Module.load (node:internal/modules/cjs/loader:1203:32)
#16 40.26     at Module._load (node:internal/modules/cjs/loader:1019:12)
#16 40.26     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
#16 40.26     at node:internal/main/run_main_module:28:49
#16 40.26 
#16 40.26 Node.js v18.20.4"
#16 40.26 info This module is OPTIONAL, you can safely ignore this error
#16 171.0 error /app/node_modules/bcrypt: Command failed.
#16 171.0 Exit code: 1
#16 171.0 Command: node-pre-gyp install --fallback-to-build
#16 171.0 Arguments: 
#16 171.0 Directory: /app/node_modules/bcrypt
#16 171.0 Output:
#16 171.0 node-pre-gyp info it worked if it ends with ok
#16 171.0 node-pre-gyp info using node-pre-gyp@1.0.11
#16 171.0 node-pre-gyp info using node@18.20.4 | linux | x64
#16 171.0 node-pre-gyp info check checked for "/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" (not found)
#16 171.0 node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.1.1/bcrypt_lib-v5.1.1-napi-v3-linux-x64-glibc.tar.gz
#16 171.0 node-pre-gyp ERR! install request to https://objects.githubusercontent.com/github-production-release-asset-2e65be/611333/248fe5e4-8167-4c00-a22a-6f3733d6efbc?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240925%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240925T100033Z&X-Amz-Expires=300&X-Amz-Signature=2bce95feb0854f1ef37655f9aebe600aebb4aeab6a56dc0b57e76ad5f57ac827&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dbcrypt_lib-v5.1.1-napi-v3-linux-x64-glibc.tar.gz&response-content-type=application%2Foctet-stream failed, reason: connect ETIMEDOUT 185.199.110.133:443 
#16 171.0 node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.1.1 and node@18.20.4 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
#16 171.0 node-pre-gyp WARN Hit error request to https://objects.githubusercontent.com/github-production-release-asset-2e65be/611333/248fe5e4-8167-4c00-a22a-6f3733d6efbc?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240925%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240925T100033Z&X-Amz-Expires=300&X-Amz-Signature=2bce95feb0854f1ef37655f9aebe600aebb4aeab6a56dc0b57e76ad5f57ac827&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dbcrypt_lib-v5.1.1-napi-v3-linux-x64-glibc.tar.gz&response-content-type=application%2Foctet-stream failed, reason: connect ETIMEDOUT 185.199.110.133:443 
#16 171.0 gyp info it worked if it ends with ok
#16 171.0 gyp info using node-gyp@10.1.0
#16 171.0 gyp info using node@18.20.4 | linux | x64
#16 171.0 gyp info ok 
#16 171.0 gyp info it worked if it ends with ok
#16 171.0 gyp info using node-gyp@10.1.0
#16 171.0 gyp info using node@18.20.4 | linux | x64
#16 171.0 gyp ERR! find Python 
#16 171.0 gyp ERR! find Python Python is not set from command line or npm configuration
#16 171.0 gyp ERR! find Python Python is not set from environment variable PYTHON
#16 171.0 gyp ERR! find Python checking if "python3" can be used
#16 171.0 gyp ERR! find Python - executable path is ""
#16 171.0 gyp ERR! find Python - "" could not be run
#16 171.0 gyp ERR! find Python checking if "python" can be used
#16 171.0 gyp ERR! find Python - executable path is ""
#16 171.0 gyp ERR! find Python - "" could not be run
#16 171.0 gyp ERR! find Python 
#16 171.0 gyp ERR! find Python **********************************************************`

Can I ask for some help here regarding the above issue? Thanks!

**Comment by vieiralucas** [comment]
Hi @eluyutao thanks for your issue.

Can you tell me a bit more about what is your end goal here?

Are you trying to run Briefer in dev mode? If so, can you try following this?
https://github.com/briefercloud/briefer/blob/main/.github/CONTRIBUTING.md#computer-running-briefer-in-dev-mode

What is your environment like, is this linux, windows, mac?
