### ISSUE TITLE
Permission denied in `jupyter_server` development docker service

### ISSUE THREAD

**Issue by vtfg** [briefercloud/briefer#34]
I tried to follow the CONTRIBUTING.md's development mode guide but Jupyter Server keeps throwing this error:

```
briefer_jupyter_server_dev  | [I 2024-09-12 21:06:00.470 ServerApp] Extension package jupyterlab took 0.1734s to import
briefer_jupyter_server_dev  | Both `sys_prefix` and `user` level settings are read-only, cannot auto-migrate `disabledExtensions` to `lockedExtensions`
briefer_jupyter_server_dev  | [I 2024-09-12 21:06:00.632 ServerApp] jupyter_briefer_extension | extension was successfully linked.
briefer_jupyter_server_dev  | [I 2024-09-12 21:06:00.632 ServerApp] jupyter_lsp | extension was successfully linked.
briefer_jupyter_server_dev  | [I 2024-09-12 21:06:00.638 ServerApp] jupyter_server_terminals | extension was successfully linked.
briefer_jupyter_server_dev  | [I 2024-09-12 21:06:00.646 ServerApp] jupyterlab | extension was successfully linked.
briefer_jupyter_server_dev  | [I 2024-09-12 21:06:00.654 ServerApp] notebook | extension was successfully linked.
briefer_jupyter_server_dev  | [W 2024-09-12 21:06:00.671 ServerApp] notebook_shim | error linking extension: [Errno 13] Permission denied: '/home/jupyteruser/.local'
```

## How to reproduce

- Create a new Github Codespace 
  > This happens in my local machine (Windows 11 with WSL 2) and in a fresh Ubuntu 22.04 installation, but it's easier to reproduce with a Codespace
- Install node v18.20.4 (lts/hydrogen) with `nvm`
- Run `./start-dev.sh`

**Comment by Shivansh-Khunger** [comment]
This happened to me as well, still zeroing in on the root cause. Tried changing `jupyter.Dockerfile` but it did not work.

**Comment by Cauatn** [comment]
same, Windows 11 with, wsl 

```briefer_jupyter_server_dev  | [I 2024-09-13 17:55:16.454 ServerApp] http://f72fba5d4ff7:8888/?token=...                                                               
briefer_jupyter_server_dev  | [I 2024-09-13 17:55:16.456 ServerApp]     http://127.0.0.1:8888/?token=...                                                              
briefer_jupyter_server_dev  | [I 2024-09-13 17:55:16.456 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).         
briefer_jupyter_server_dev  | Traceback (most recent call last):
briefer_jupyter_server_dev  |   File "/usr/local/bin/jupyter-server", line 8, in <module>
briefer_jupyter_server_dev  |     sys.exit(main())                                                                                                                    
briefer_jupyter_server_dev  |   File "/usr/local/lib/python3.9/site-packages/jupyter_core/application.py", line 283, in launch_instance                               
briefer_jupyter_server_dev  |     super().launch_instance(argv=argv, **kwargs)
briefer_jupyter_server_dev  |   File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 1075, in launch_instance                          
briefer_jupyter_server_dev  |     app.start()                                                                                                                         
briefer_jupyter_server_dev  |   File "/usr/local/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 2967, in start                                        
briefer_jupyter_server_dev  |     self.start_app()                                                                                                                    
briefer_jupyter_server_dev  |   File "/usr/local/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 2868, in start_app                                    
briefer_jupyter_server_dev  |     self.write_server_info_file()                                                                                                       
briefer_jupyter_server_dev  |   File "/usr/local/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 2674, in write_server_info_file                       
briefer_jupyter_server_dev  |     with secure_write(self.info_file) as f:
briefer_jupyter_server_dev  |   File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__                                                                 
briefer_jupyter_server_dev  |     return next(self.gen)                                                                                                               
briefer_jupyter_server_dev  |   File "/usr/local/lib/python3.9/site-packages/jupyter_core/paths.py", line 1007, in secure_write                                       
briefer_jupyter_server_dev  |     raise RuntimeError(msg)                                                                                                             
briefer_jupyter_server_dev  | RuntimeError: Permissions assignment failed for secure file: '/home/jupyteruser/.local/share/jupyter/runtime/jpserver-8.json'. Got '0o677' instead of '0o0600'.                                                                                                                                               ````

**Comment by vtfg** [comment]
Someone on Slack (he/she hid his name) fixed this by running these commands:

```
mkdir -p ./jupyterfiles
sudo chown -R $(whoami):$(whoami) ./jupyterfiles
mkdir -p ./jupyterfiles/.local/share/jupyter
```

Restart the `jupyer_server` container after executing.

Would be nice if we added them to the `start-dev` script.

**Comment by vtfg** [comment]
The fix got added to the `CONTRIBUTING.md` file.
